from collections.abc import Iterable, Iterator, Sequence
from typing import TypeAlias

import numpy as np
import numpy.typing as npt

PointLike: TypeAlias = Sequence[float] | npt.ArrayLike
PointsLike: TypeAlias = Sequence[Sequence[float]] | npt.ArrayLike
SimplexLike: TypeAlias = Sequence[int]
Simplex: TypeAlias = tuple[int, ...]
SimplexSet: TypeAlias = set[Simplex]
TransformLike: TypeAlias = Sequence[Sequence[float]] | npt.ArrayLike

__version__: str


class Triangulation:
    def __init__(self, coords: PointsLike) -> None: ...

    @property
    def vertices(self) -> list[tuple[float, ...]]: ...

    @property
    def simplices(self) -> SimplexSet: ...

    @property
    def vertex_to_simplices(self) -> list[SimplexSet]: ...

    @property
    def hull(self) -> set[int]: ...

    @property
    def dim(self) -> int: ...

    @property
    def default_transform(self) -> npt.NDArray[np.float64]: ...

    def add_simplex(self, simplex: SimplexLike) -> None: ...
    def delete_simplex(self, simplex: SimplexLike) -> None: ...
    def add_point(
        self,
        point: PointLike,
        simplex: SimplexLike | None = None,
        transform: TransformLike | None = None,
    ) -> tuple[SimplexSet, SimplexSet]: ...
    def get_vertices(self, indices: Sequence[int]) -> list[tuple[float, ...]]: ...
    def locate_point(self, point: PointLike) -> tuple[int, ...]: ...
    def get_reduced_simplex(
        self,
        point: PointLike,
        simplex: SimplexLike,
        eps: float = 1e-8,
    ) -> list[int]: ...
    def circumscribed_circle(
        self,
        simplex: SimplexLike,
        transform: TransformLike | None = None,
    ) -> tuple[tuple[float, ...], float]: ...
    def point_in_circumcircle(
        self,
        pt_index: int,
        simplex: SimplexLike,
        transform: TransformLike | None = None,
    ) -> bool: ...
    def point_in_cicumcircle(
        self,
        pt_index: int,
        simplex: SimplexLike,
        transform: TransformLike | None = None,
    ) -> bool: ...
    def volume(self, simplex: SimplexLike) -> float: ...
    def volumes(self) -> list[float]: ...
    def faces(
        self,
        dim: int | None = None,
        simplices: Iterable[SimplexLike] | None = None,
        vertices: Iterable[int] | None = None,
    ) -> Iterator[Simplex]: ...
    def containing(self, face: Sequence[int]) -> SimplexSet: ...
    def reference_invariant(self) -> bool: ...
    def point_in_simplex(
        self,
        point: PointLike,
        simplex: SimplexLike,
        eps: float = 1e-8,
    ) -> bool: ...
    def bowyer_watson(
        self,
        pt_index: int,
        containing_simplex: SimplexLike | None = None,
        transform: TransformLike | None = None,
    ) -> tuple[SimplexSet, SimplexSet]: ...
    def vertex_invariant(self, vertex: int) -> bool: ...
    def convex_invariant(self, vertex: int) -> bool: ...


def circumsphere(points: PointsLike) -> tuple[tuple[float, ...], float]: ...
def fast_2d_circumcircle(points: PointsLike) -> tuple[tuple[float, ...], float]: ...
def fast_2d_point_in_simplex(point: PointLike, simplex: PointsLike, eps: float = 1e-8) -> bool: ...
def fast_3d_circumcircle(points: PointsLike) -> tuple[tuple[float, ...], float]: ...
def fast_3d_circumsphere(points: PointsLike) -> tuple[tuple[float, ...], float]: ...
def fast_norm(point: PointLike) -> float: ...
def orientation(face: PointsLike, origin: PointLike) -> int: ...
def point_in_simplex(point: PointLike, simplex: PointsLike, eps: float = 1e-8) -> bool: ...
def simplex_volume_in_embedding(vertices: PointsLike) -> float: ...
def volume(simplex: PointsLike) -> float: ...
