from collections.abc import Iterable, Iterator, Sequence
from typing import TypeAlias

import numpy as np
import numpy.typing as npt

PointLike: TypeAlias = Sequence[float] | npt.ArrayLike
PointsLike: TypeAlias = Sequence[Sequence[float]] | npt.ArrayLike
SimplexLike: TypeAlias = Sequence[int]
Simplex: TypeAlias = tuple[int, ...]
SimplexSet: TypeAlias = set[Simplex]
CircumscribedCircle: TypeAlias = tuple[tuple[float, ...], float]
TransformLike: TypeAlias = Sequence[Sequence[float]] | npt.ArrayLike

__version__: str

class Learner1D:
    def __init__(
        self,
        bounds: tuple[float, float],
        loss_per_interval: object | None = None,
    ) -> None: ...
    def tell(self, x: float, y: float | Sequence[float]) -> None: ...
    def tell_many(
        self,
        xs: list[float],
        ys: list[float | Sequence[float]],
        force: bool = False,
    ) -> None: ...
    def tell_pending(self, x: float) -> None: ...
    def ask(
        self, n: int, tell_pending: bool = True
    ) -> tuple[list[float], list[float]]: ...
    def run(
        self,
        f: object,
        *,
        goal: float | None = None,
        n_points: int | None = None,
        batch_size: int = 1,
    ) -> int: ...
    @property
    def loss(self) -> float: ...
    @property
    def npoints(self) -> int: ...
    @property
    def vdim(self) -> int | None: ...
    def to_numpy(
        self,
    ) -> tuple[npt.NDArray[np.float64], npt.NDArray[np.float64]]: ...
    def remove_unfinished(self) -> None: ...
    @property
    def pending_points(self) -> list[float]: ...
    @property
    def data(self) -> dict[float, float | list[float]]: ...
    def intervals(self) -> list[tuple[float, float, float]]: ...
    @property
    def bounds(self) -> tuple[float, float]: ...

class SimplicesProxy:
    def __contains__(self, simplex: Simplex) -> bool: ...
    def __iter__(self) -> Iterator[Simplex]: ...
    def __len__(self) -> int: ...

class VerticesProxy:
    def __getitem__(self, index: int) -> tuple[float, ...]: ...
    def __iter__(self) -> Iterator[tuple[float, ...]]: ...
    def __len__(self) -> int: ...

class VertexToSimplicesProxy:
    def __getitem__(self, index: int) -> SimplexSet: ...
    def __iter__(self) -> Iterator[SimplexSet]: ...
    def __len__(self) -> int: ...

class Triangulation:
    def __init__(self, coords: PointsLike) -> None: ...
    @property
    def vertices(self) -> VerticesProxy: ...
    @property
    def simplices(self) -> SimplicesProxy: ...
    @property
    def vertex_to_simplices(self) -> VertexToSimplicesProxy: ...
    @property
    def hull(self) -> set[int]: ...
    @property
    def dim(self) -> int: ...
    @property
    def default_transform(self) -> npt.NDArray[np.float64]: ...
    def add_simplex(self, simplex: SimplexLike) -> None: ...
    def delete_simplex(self, simplex: SimplexLike) -> None: ...
    def has_simplex(self, simplex: Simplex) -> bool: ...
    def add_point(
        self,
        point: PointLike,
        simplex: SimplexLike | None = None,
        transform: TransformLike | None = None,
    ) -> tuple[SimplexSet, SimplexSet]: ...
    def get_vertices(self, indices: Sequence[int]) -> list[tuple[float, ...]]: ...
    def locate_point(self, point: PointLike) -> tuple[int, ...]: ...
    def get_reduced_simplex(
        self,
        point: PointLike,
        simplex: SimplexLike,
        eps: float = 1e-8,
    ) -> list[int]: ...
    def circumscribed_circle(
        self,
        simplex: SimplexLike,
        transform: TransformLike | None = None,
    ) -> CircumscribedCircle: ...
    def point_in_circumcircle(
        self,
        pt_index: int,
        simplex: SimplexLike,
        transform: TransformLike | None = None,
    ) -> bool: ...
    def point_in_cicumcircle(
        self,
        pt_index: int,
        simplex: SimplexLike,
        transform: TransformLike | None = None,
    ) -> bool: ...
    def volume(self, simplex: SimplexLike) -> float: ...
    def volumes(self) -> list[float]: ...
    def faces(
        self,
        dim: int | None = None,
        simplices: Iterable[SimplexLike] | None = None,
        vertices: Iterable[int] | None = None,
    ) -> Iterator[Simplex]: ...
    def containing(self, face: Sequence[int]) -> SimplexSet: ...
    def reference_invariant(self) -> bool: ...
    def vertex_to_simplices_for(self, vertex: int) -> SimplicesProxy: ...
    def point_in_simplex(
        self,
        point: PointLike,
        simplex: SimplexLike,
        eps: float = 1e-8,
    ) -> bool: ...
    def bowyer_watson(
        self,
        pt_index: int,
        containing_simplex: SimplexLike | None = None,
        transform: TransformLike | None = None,
    ) -> tuple[SimplexSet, SimplexSet]: ...
    def vertex_invariant(self, vertex: int) -> bool: ...
    def convex_invariant(self, vertex: int) -> bool: ...

def circumsphere(points: PointsLike) -> tuple[tuple[float, ...], float]: ...
def fast_2d_circumcircle(points: PointsLike) -> tuple[tuple[float, ...], float]: ...
def fast_2d_point_in_simplex(point: PointLike, simplex: PointsLike, eps: float = 1e-8) -> bool: ...
def fast_3d_circumcircle(points: PointsLike) -> tuple[tuple[float, ...], float]: ...
def fast_3d_circumsphere(points: PointsLike) -> tuple[tuple[float, ...], float]: ...
def fast_norm(point: PointLike) -> float: ...
def orientation(face: PointsLike, origin: PointLike) -> int: ...
def point_in_simplex(point: PointLike, simplex: PointsLike, eps: float = 1e-8) -> bool: ...
def simplex_volume_in_embedding(vertices: PointsLike) -> float: ...
def volume(simplex: PointsLike) -> float: ...
